# Generated by Django 6.0.2 on 2026-02-26 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsac', '0002_atendente_categoria_cliente_remove_sale_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamacao',
            name='email_contato',
            field=models.EmailField(default='', max_length=100, verbose_name='E-mail de contato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reclamacao',
            name='nome_cliente',
            field=models.CharField(default=1, max_length=150, verbose_name='Nome no formulário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reclamacao',
            name='telefone_contato',
            field=models.CharField(default='', max_length=20, verbose_name='Telefone de contato'),
            preserve_default=False,
        ),
    ]
