# Generated by Django 6.0.2 on 2026-02-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsac', '0003_reclamacao_email_contato_reclamacao_nome_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendente',
            name='id_atendente',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id_categoria',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_cliente',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reclamacao',
            name='id_reclamacao',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
